version: '3.8'

services:
  db:
    image: mysql
    container_name: db
    env_file:
      - .env
    ports:
      - "$DOCKER_MYSQL_PORT:$DB_PORT"
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: $DB_DATABASE
    volumes:
      - ./database/mysql:/d/github/labook

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    image: joaofilippe/labook-api
    container_name: labook-api
    build: .
    env_file:
      - .env
    ports:
      - $DOCKER_NODE_PORT:$PORT
    depends_on:
      - db
    restart: always
